POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Puppeteer: What can I do?",
    "author": "Google Developers",
    "url": "https://developers.google.com/web/tools/puppeteer",
    "likes": 150
}

